import type {
  CommunityPost,
  HealthBuddy,
  HealthChallenge,
  HealthGroup,
  WeeklyReport,
  CommunityProfile,
  BuddySuggestion,
} from './types';

export const MOCK_COMMUNITY_PROFILE: CommunityProfile = {
  displayName: 'You',
  healthLevel: 12,
  healthScore: 78,
  xp: 2840,
  coins: 450,
  followers: 24,
  following: 18,
  postsCount: 3,
  contributionScore: 156,
  badges: ['Starter'],
};

export const MOCK_WEEKLY_REPORT: WeeklyReport = {
  weekLabel: 'Mar 24 – Mar 30',
  healthScoreChange: 4,
  medicineAdherence: 92,
  stepsTotal: 42100,
  waterGlasses: 48,
  sleepAverage: '7h 12m',
  streakSummary: '14-day medicine streak · 7-day check-in',
  topAchievement: 'Completed Walk 10K challenge milestone',
  aiRecommendation:
    'Great week. Keep your medicine routine. Schedule your due lab test early next week.',
};

export const MOCK_POSTS: CommunityPost[] = [
  {
    id: 'p0',
    authorName: 'Abdullah',
    authorRole: 'user',
    content: 'Started walking 20 minutes daily. Feeling better this week.',
    category: 'General health',
    likes: 18,
    comments: 2,
    commentList: [
      {
        id: 'c0a',
        authorName: 'Hira S.',
        isAnonymous: false,
        content: 'Keep it up — consistency beats intensity.',
        timeAgo: '4h',
      },
      {
        id: 'c0b',
        authorName: 'Omar T.',
        isAnonymous: false,
        content: 'Same goal here. Want to join the Walking Club group?',
        timeAgo: '2h',
      },
    ],
    isVerified: false,
    isAnonymous: false,
    timeAgo: '1 day',
    postType: 'text',
    healthContribution: 8,
  },
  {
    id: 'p1',
    authorName: 'Dr. Ayesha Khan',
    authorRole: 'doctor',
    content:
      'Managing diabetes in Ramadan: check blood sugar before iftar, stay hydrated, and do not skip Suhoor without medical advice.',
    category: 'Diabetes',
    likes: 234,
    comments: 2,
    commentList: [
      {
        id: 'c1',
        authorName: 'Ali R.',
        isAnonymous: false,
        content: 'Very helpful. Should I reduce insulin before iftar?',
        timeAgo: '1h',
      },
      {
        id: 'c2',
        authorName: 'Dr. Ayesha Khan',
        isAnonymous: false,
        content:
          'Please consult your doctor for insulin adjustments. Never change doses alone.',
        timeAgo: '45m',
        isVerified: true,
      },
    ],
    isVerified: true,
    isAnonymous: false,
    timeAgo: '2h',
    healthContribution: 45,
    postType: 'text',
  },
  {
    id: 'p2',
    authorName: 'Anonymous',
    authorRole: 'user',
    content:
      'Struggling with anxiety before sleep. Does anyone have a simple night routine that helped them?',
    category: 'Mental Wellness',
    likes: 67,
    comments: 1,
    commentList: [
      {
        id: 'c3',
        authorName: 'Sana M.',
        isAnonymous: false,
        content:
          'Deep breathing for 5 minutes and no phone 30 min before bed helped me.',
        timeAgo: '3h',
      },
    ],
    isVerified: false,
    isAnonymous: true,
    timeAgo: '5h',
    healthContribution: 12,
    postType: 'text',
  },
  {
    id: 'p3',
    authorName: 'Nutritionist Sara',
    authorRole: 'nutritionist',
    content:
      'PCOS breakfast ideas: eggs with spinach, Greek yogurt with nuts, or daliya with flaxseed. Protein helps morning energy.',
    category: 'Nutrition',
    likes: 156,
    comments: 0,
    commentList: [],
    isVerified: true,
    isAnonymous: false,
    timeAgo: '1d',
    healthContribution: 38,
    postType: 'text',
  },
  {
    id: 'p4',
    authorName: 'Ahmed K.',
    authorRole: 'user',
    content: 'Day 14 of my medicine streak. Small wins matter.',
    category: 'Success Story',
    likes: 89,
    comments: 0,
    commentList: [],
    isVerified: false,
    isAnonymous: false,
    timeAgo: '1d',
    healthContribution: 20,
    postType: 'text',
  },
  {
    id: 'p5',
    authorName: 'Fatima N.',
    authorRole: 'user',
    content:
      'Joined the Diabetes Care group last week. Already learned so much from others managing HbA1c. Grateful for this community.',
    category: 'Diabetes',
    likes: 42,
    comments: 3,
    commentList: [
      {
        id: 'c5a',
        authorName: 'Bilal H.',
        isAnonymous: false,
        content: 'Welcome! The weekly topic threads are gold.',
        timeAgo: '6h',
      },
    ],
    isVerified: false,
    isAnonymous: false,
    timeAgo: '8h',
    healthContribution: 15,
    postType: 'text',
    groupName: 'Diabetes Care',
  },
  {
    id: 'p6',
    authorName: 'Dr. Hassan Ali',
    authorRole: 'psychologist',
    content:
      'Quick tip: name your worry for 60 seconds, then write one tiny next step. Naming reduces overwhelm more than scrolling does.',
    category: 'Mental Wellness',
    likes: 118,
    comments: 1,
    commentList: [],
    isVerified: true,
    isAnonymous: false,
    timeAgo: '12h',
    healthContribution: 40,
    postType: 'text',
  },
  {
    id: 'p7',
    authorName: 'Zain K.',
    authorRole: 'user',
    content:
      'Hit 8,000 steps yesterday for the first time in months. The 10K challenge is motivating me more than I expected.',
    category: 'Success Story',
    likes: 53,
    comments: 2,
    commentList: [],
    isVerified: false,
    isAnonymous: false,
    timeAgo: '3h',
    healthContribution: 18,
    postType: 'text',
  },
  {
    id: 'p8',
    authorName: 'Ayesha M.',
    authorRole: 'user',
    content:
      'Lab results came back clearer after sticking to my medicine schedule. Sharing in case someone needs a reminder that adherence pays off.',
    category: 'Recovery',
    likes: 71,
    comments: 4,
    commentList: [],
    isVerified: false,
    isAnonymous: false,
    timeAgo: '6h',
    healthContribution: 22,
    postType: 'text',
  },
  {
    id: 'p9',
    authorName: 'Physio Imran',
    authorRole: 'physiotherapist',
    content:
      'Desk stretch for neck pain: chin tucks ×10, shoulder rolls ×10, every 90 minutes. Stop if pain sharpens — see a clinician.',
    category: 'Health Tips',
    likes: 97,
    comments: 0,
    commentList: [],
    isVerified: true,
    isAnonymous: false,
    timeAgo: '10h',
    healthContribution: 35,
    postType: 'text',
  },
];

export const MOCK_GROUPS: HealthGroup[] = [
  {
    id: 'g1',
    name: 'Diabetes Care',
    description: 'Tips and support for diabetes management.',
    icon: 'water',
    memberCount: 24,
    postCount: 8,
    isJoined: true,
    moderators: ['Community Team'],
    verifiedDoctors: ['Dr. Ayesha Khan'],
  },
  {
    id: 'g2',
    name: 'Walking Club',
    description: 'Daily walking motivation.',
    icon: 'walk',
    memberCount: 14,
    postCount: 3,
    isJoined: false,
    moderators: ['FitPak Team'],
    verifiedDoctors: [],
  },
  {
    id: 'g3',
    name: 'PCOS Support',
    description: 'Hormone health, nutrition, and emotional support.',
    icon: 'heart-pulse',
    memberCount: 82,
    postCount: 12,
    isJoined: false,
    moderators: ['Sara Nutrition'],
    verifiedDoctors: ['Dr. Fatima Noor'],
  },
  {
    id: 'g4',
    name: 'Mental Wellness',
    description: 'Safe discussions about stress, anxiety, and self-care.',
    icon: 'brain',
    memberCount: 151,
    postCount: 21,
    isJoined: true,
    moderators: ['Wellness Team'],
    verifiedDoctors: ['Dr. Hassan Ali'],
  },
];

export const MOCK_CHALLENGES: HealthChallenge[] = [
  {
    id: 'ch1',
    title: '10,000 Steps',
    description: 'Walk 10,000 steps daily',
    icon: 'walk',
    color: '#059669',
    progress: 4200,
    target: 10000,
    unit: 'steps',
    daysLeft: 6,
    isJoined: true,
    participants: 342,
    xpReward: 100,
    badgeName: 'Achiever',
    leaderboard: [
      { id: 'u1', name: 'You', progress: 4200, rank: 12, isFriend: true },
      { id: 'u2', name: 'Hira S.', progress: 9800, rank: 1, isFriend: true },
    ],
  },
  {
    id: 'ch2',
    title: 'Medicine Adherence',
    description: 'Take all scheduled medicines on time',
    icon: 'pill',
    color: '#6366F1',
    progress: 14,
    target: 30,
    unit: 'doses',
    daysLeft: 16,
    isJoined: true,
    participants: 189,
    xpReward: 300,
    badgeName: 'Adherence Hero',
    leaderboard: [
      { id: 'u1', name: 'You', progress: 14, rank: 8, isFriend: true },
    ],
  },
  {
    id: 'ch3',
    title: 'Water Reminder',
    description: 'Drink 8 glasses daily',
    icon: 'cup-water',
    color: '#2563EB',
    progress: 5,
    target: 8,
    unit: 'glasses',
    daysLeft: 3,
    isJoined: false,
    participants: 560,
    xpReward: 50,
    badgeName: 'Hydration Star',
    leaderboard: [],
  },
  {
    id: 'ch4',
    title: 'Morning Workout',
    description: 'Exercise 30 minutes daily',
    icon: 'run',
    color: '#7C3AED',
    progress: 0,
    target: 30,
    unit: 'minutes',
    daysLeft: 14,
    isJoined: false,
    participants: 210,
    xpReward: 150,
    badgeName: 'Active',
    leaderboard: [],
  },
];

export const MOCK_BUDDIES: HealthBuddy[] = [
  {
    id: 'b1',
    name: 'Hira S.',
    relation: 'friend',
    streakDays: 21,
    lastEncouragement: 'You got this!',
    isOnline: true,
  },
  {
    id: 'b2',
    name: 'Ali R.',
    relation: 'family',
    streakDays: 14,
    isOnline: false,
  },
  {
    id: 'b3',
    name: 'Sana M.',
    relation: 'workout',
    streakDays: 9,
    lastEncouragement: 'Great walk today',
    isOnline: true,
  },
];

/** People you can add — from groups, challenges, or community */
export const MOCK_BUDDY_SUGGESTIONS: BuddySuggestion[] = [
  {
    id: 's1',
    name: 'Omar T.',
    subtitle: 'Also in Walk 10,000 Steps challenge',
    source: 'challenge',
    healthLevel: 9,
  },
  {
    id: 's2',
    name: 'Fatima N.',
    subtitle: 'Member of Diabetes Pakistan group',
    source: 'group',
    healthLevel: 11,
  },
  {
    id: 's3',
    name: 'Zain K.',
    subtitle: 'Posted in Mental Wellness group',
    source: 'community',
    healthLevel: 7,
  },
  {
    id: 's4',
    name: 'Ayesha M.',
    subtitle: 'Joined Medicine Adherence challenge',
    source: 'challenge',
    healthLevel: 14,
  },
  {
    id: 's5',
    name: 'Bilal H.',
    subtitle: 'Member of Fitness & Weight Loss group',
    source: 'group',
    healthLevel: 10,
  },
];

export const BUDDY_RELATIONS: { id: HealthBuddy['relation']; label: string }[] = [
  { id: 'friend', label: 'Friend' },
  { id: 'family', label: 'Family' },
  { id: 'workout', label: 'Workout partner' },
  { id: 'partner', label: 'Accountability partner' },
];

export const ANONYMOUS_CATEGORIES = [
  'Mental Wellness',
  'Sexual Health',
  'Pregnancy',
  'Addiction Support',
  'Depression',
  'Anxiety',
];

export const FEED_FILTERS: { id: import('./types').FeedFilter; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'videos', label: 'Videos' },
  { id: 'photos', label: 'Photos' },
  { id: 'verified', label: 'Verified' },
];
